#ifndef ACTIONS_H
#define ACTIONS_H
#include <Engine/Core/Trigger/Action/ChangeNameAction/ChangeNameAction.h>
#include <Engine/Core/Trigger/Action/CreateTimerAction/CreateTimerAction.h>
#include <Engine/Core/Trigger/Action/GetSystemTimeAction/GetSystemTimeAction.h>
#include <Engine/Core/Trigger/Action/CreateTriggerAction/CreateTriggerAction.h>
#include <Engine/Core/Trigger/Action/CheckEqualityAction/CheckEqualityAction.h>
#include <Engine/Core/Trigger/Action/LoadAssetAction/LoadAssetAction.h>
#include <Engine/Core/Trigger/Action/SwapItemsAction/SwapItemAction/SwapItemAction.h>
#include <Engine/Core/Trigger/Action/SwapItemsAction/SwapIndexAction/SwapIndexAction.h>
#include <Engine/Core/Trigger/Action/SwapItemsAction/SwapListAction/SwapListAction.h>
#include <Engine/Core/Trigger/Action/SetPublicTextureAction/SetPublicTextureAction.h>
#include <Engine/Core/Trigger/Action/CheckPropertyAction/CheckPropertyAction.h>
#include <Engine/Core/Trigger/Action/EnablePropertyAction/EnablePropertyAction.h>
#include <Engine/Core/Trigger/Action/CreateSetAction/CreateSetAction.h>
#include <Engine/Core/Trigger/Action/GetAmountOfSlotsAction/GetAmountOfSlotsAction.h>
#include <Engine/Core/Trigger/Action/ResizeSetAction/ResizeSetAction.h>
#include <Engine/Core/Trigger/Action/GetDataFromSlotAction/GetDataFromSlotAction.h>
#include <Engine/Core/Trigger/Action/SetDataToSlotAction/SetDataToSlotAction.h>
#include <Engine/Core/Trigger/Action/EnableRotationRangeAction/EnableRotationRangeAction.h>
#include <Engine/Core/Trigger/Action/ChangeRotationRangeAction/ChangeRotationRangeAction.h>
#include <Engine/Core/Trigger/Action/EnableRotationAction/EnableRotationAction.h>
#include <Engine/Core/Trigger/Action/AddInputEventAction/AddInputEventAction.h>
#include <Engine/Core/Trigger/Action/ClearInputEventsAction/ClearInputEventsAction.h>
#include <Engine/Core/Trigger/Action/CheckTileExistAction/CheckTileExistAction.h>
#include <Engine/Core/Trigger/Action/CheckTileSolidAction/CheckTileSolidAction.h>
#include <Engine/Core/Trigger/Action/CheckTilePassAction/CheckTilePassAction.h>
#include <Engine/Core/Trigger/Action/CreatePlayerControlAction/CreatePlayerControlAction.h>
#include <Engine/Core/Trigger/Action/ChangeTilePassAction/ChangeTilePassAction.h>
#include <Engine/Core/Trigger/Action/ChangeInputTimingAction/ChangeInputTimingAction.h>
#include <Engine/Core/Trigger/Action/ChangeZoomFarAction/ChangeZoomFarAction.h>
#include <Engine/Core/Trigger/Action/ChangeZoomNearAction/ChangeZoomNearAction.h>
#include <Engine/Core/Trigger/Action/ChangeZoomSpeedAction/ChangeZoomSpeedAction.h>
#include <Engine/Core/Trigger/Action/EnableZoomAction/EnableZoomAction.h>
#include <Engine/Core/Trigger/Action/ReplayAction/ReplayAction.h>
#include <Engine/Core/Trigger/Action/CopyTileAction/CopyTileAction.h>
#include <Engine/Core/Trigger/Action/GetBrushOfTileAction/GetBrushOfTileAction.h>
#include <Engine/Core/Trigger/Action/SwapTwoTilesAction/SwapTwoTilesAction.h>
#include <Engine/Core/Trigger/Action/SetOneInputEventAction/SetOneInputEventAction.h>
#include <Engine/Core/Trigger/Action/CreateCameraAction/CreateCameraAction.h>
#include <Engine/Core/Trigger/Action/MoveTileFromToAction/MoveTileFromToAction.h>
#include <Engine/Core/Trigger/Action/ChangeRotationModeAction/ChangeRotationModeAction.h>
#include <Engine/Core/Trigger/Action/ChangeMovementModeAction/ChangeMovementModeAction.h>
#include <Engine/Core/Trigger/Action/SetPublicTileAction/SetPublicTileAction.h>
#include <Engine/Core/Trigger/Action/SetPrivateAssetAction/SetPrivateAssetAction.h>
#include <Engine/Core/Trigger/Action/GetFloatLerpCurrentAction/GetFloatLerpCurrentAction.h>
#include <Engine/Core/Trigger/Action/GetFloatLerpDeltaAction/GetFloatLerpDeltaAction.h>
#include <Engine/Core/Trigger/Action/ChangeValueRangeAction/ChangeIntegerValueRangeAction/ChangeIntegerValueRangeAction.h>
#include <Engine/Core/Trigger/Action/ChangeValueRangeAction/ChangeFloatValueRangeAction/ChangeFloatValueRangeAction.h>
#include <Engine/Core/Trigger/Action/GetControlVectorsAction/GetControlVectorsAction.h>
#include <Engine/Core/Trigger/Action/EnableStaticObjectAction/EnableStaticObjectAction.h>
#include <Engine/Core/Trigger/Action/CreateTextureAction/CreateTextureAction.h>
#include <Engine/Core/Trigger/Action/CreateMeshAction/CreateMeshAction.h>
#include <Engine/Core/Trigger/Action/RemoveBrushAction/RemoveBrushAction.h>
#include <Engine/Core/Trigger/Action/CreateTexturedAnimationAction/CreateTexturedAnimationAction.h>
#include <Engine/Core/Trigger/Action/GetControlQuaternionsAction/GetControlQuaternionsAction.h>
#include <Engine/Core/Trigger/Action/GetRadiusFrom2PointsAction/GetRadiusFrom2PointsAction.h>
#include <Engine/Core/Trigger/Action/GetRadiusFrom3PointsAction/GetRadiusFrom3PointsAction.h>
#include <Engine/Core/Trigger/Action/ChangeValueAction/ChangeIntegerValueAction/ChangeIntegerValueAction.h>
#include <Engine/Core/Trigger/Action/ChangeValueAction/ChangeFloatValueAction/ChangeFloatValueAction.h>
#include <Engine/Core/Trigger/Action/ChangeValueAction/ChangeBooleanValueAction/ChangeBooleanValueAction.h>
#include <Engine/Core/Trigger/Action/ChangeValueAction/ChangeStringValueAction/ChangeStringValueAction.h>
#include <Engine/Core/Trigger/Action/ChangeValueAction/ChangeVector2ValueAction/ChangeVector2ValueAction.h>
#include <Engine/Core/Trigger/Action/ChangeValueAction/ChangeVector3ValueAction/ChangeVector3ValueAction.h>
#include <Engine/Core/Trigger/Action/ChangeValueAction/ChangeQuaternionValueAction/ChangeQuaternionValueAction.h>
#include <Engine/Core/Trigger/Action/GetNameAction/GetNameAction.h>
#include <Engine/Core/Trigger/Action/VectorToSphericalAction/Vector2ToSphericalAction/Vector2ToSphericalAction.h>
#include <Engine/Core/Trigger/Action/VectorToSphericalAction/Vector3ToSphericalAction/Vector3ToSphericalAction.h>
#include <Engine/Core/Trigger/Action/GetCameraLookAction/GetCameraLookAction.h>
#include <Engine/Core/Trigger/Action/GetLineDirectionAction/GetLineDirectionAction.h>
#include <Engine/Core/Trigger/Action/EnableShowAction/EnableShowAction.h>
#include <Engine/Core/Trigger/Action/RotateListAction/RotateListAction.h>
#include <Engine/Core/Trigger/Action/CheckListEmptyAction/CheckListEmptyAction.h>
#include <Engine/Core/Trigger/Action/MoveAroundPivotAction/MoveAroundPivotAction.h>
#include <Engine/Core/Trigger/Action/RotateAroundPivotAction/RotateAroundPivotAction.h>
#include <Engine/Core/Trigger/Action/EnableFreezeAction/EnableFreezeAction.h>
#include <Engine/Core/Trigger/Action/ChangeActivationLimitAction/ChangeActivationLimitAction.h>
#include <Engine/Core/Trigger/Action/GetViewingPointAction/GetViewingPointAction.h>
#include <Engine/Core/Trigger/Action/GetCircleLengthAction/GetCircleLengthAction.h>
#include <Engine/Core/Trigger/Action/GetLineLengthAction/GetLineLengthAction.h>
#include <Engine/Core/Trigger/Action/ChangeDeactivationModeAction/ChangeDeactivationModeAction.h>
#include <Engine/Core/Trigger/Action/GetDataFromControlVectorAction/GetDataFromControlVectorAction/GetDataFromControlVectorAction.h>
#include <Engine/Core/Trigger/Action/GetDataFromControlVectorAction/GetDataFromControlTranslatableAction/GetDataFromControlTranslatableAction.h>
#include <Engine/Core/Trigger/Action/GetDataFromControlVectorAction/GetDataFromControlScalableAction/GetDataFromControlScalableAction.h>
#include <Engine/Core/Trigger/Action/GetDataFromControlVectorAction/GetDataFromControlColorableAction/GetDataFromControlColorableAction.h>
#include <Engine/Core/Trigger/Action/CheckObjectExistAction/CheckObjectExistAction.h>
#include <Engine/Core/Trigger/Action/GetDataFromControlQuaternionAction/GetDataFromControlQuaternionAction/GetDataFromControlQuaternionAction.h>
#include <Engine/Core/Trigger/Action/GetDataFromControlQuaternionAction/GetDataFromControlRotatableAction/GetDataFromControlRotatableAction.h>
#include <Engine/Core/Trigger/Action/SendMessageAction/SendMessageAction.h>
#include <Engine/Core/Trigger/Action/DestroyObjectAction/DestroyObjectAction.h>
#include <Engine/Core/Trigger/Action/SaveToFileAction/SaveToFileAction.h>
#include <Engine/Core/Trigger/Action/GetTileCenterAction/GetTileCenterAction.h>
#include <Engine/Core/Trigger/Action/ChangeStripPointsAction/ChangeStripVectorsAction/ChangeStripVectorsAction.h>
#include <Engine/Core/Trigger/Action/ChangeStripPointsAction/ChangeStripTranslatablesAction/ChangeStripTranslatablesAction.h>
#include <Engine/Core/Trigger/Action/ChangeStripPointsAction/ChangeStripScalablesAction/ChangeStripScalablesAction.h>
#include <Engine/Core/Trigger/Action/ChangeStripPointsAction/ChangeStripColorablesAction/ChangeStripColorablesAction.h>
#include <Engine/Core/Trigger/Action/GetVectorLerpPathAction/GetVectorLerpPathAction.h>
#include <Engine/Core/Trigger/Action/ChangeAnimationFrameAction/ChangeAnimationFrameAction.h>
#include <Engine/Core/Trigger/Action/GetAmountOfFramesAction/GetAmountOfFramesAction.h>
#include <Engine/Core/Trigger/Action/GetVectorLengthAction/GetVector3LengthAction/GetVector3LengthAction.h>
#include <Engine/Core/Trigger/Action/GetVectorLengthAction/GetVector2LengthAction/GetVector2LengthAction.h>
#include <Engine/Core/Trigger/Action/GetFrameSizeAction/GetFrameSizeAction.h>
#include <Engine/Core/Trigger/Action/CheckFrustumInQuadAction/CheckFrustumInQuadAction.h>
#include <Engine/Core/Trigger/Action/CreateRotationFromToAction/CreateRotationFromVector3ToVector3Action/CreateRotationFromVector3ToVector3Action.h>
#include <Engine/Core/Trigger/Action/CreateRotationFromToAction/CreateRotationFromQuaternionToQuaternionAction/CreateRotationFromQuaternionToQuaternionAction.h>
#include <Engine/Core/Trigger/Action/ChangeAtlasAction/ChangeAtlasAction.h>
#include <Engine/Core/Trigger/Action/GetNormalizedVectorAction/GetNormalizedVector3Action/GetNormalizedVector3Action.h>
#include <Engine/Core/Trigger/Action/GetNormalizedVectorAction/GetNormalizedVector2Action/GetNormalizedVector2Action.h>
#include <Engine/Core/Trigger/Action/GetVectorComponentAction/GetVector3ComponentAction/GetVector3ComponentAction.h>
#include <Engine/Core/Trigger/Action/ChangeVectorComponentAction/ChangeVector3ComponentAction/ChangeVector3ComponentAction.h>
#include <Engine/Core/Trigger/Action/GetVectorComponentAction/GetVector2ComponentAction/GetVector2ComponentAction.h>
#include <Engine/Core/Trigger/Action/ChangeVectorComponentAction/ChangeVector2ComponentAction/ChangeVector2ComponentAction.h>
#include <Engine/Core/Trigger/Action/GetVectorLerpTAction/GetVectorLerpTAction/GetVectorLerpTAction.h>
#include <Engine/Core/Trigger/Action/GetVectorLerpTAction/GetTranslatableLerpTAction/GetTranslatableLerpTAction.h>
#include <Engine/Core/Trigger/Action/GetVectorLerpTAction/GetScalableLerpTAction/GetScalableLerpTAction.h>
#include <Engine/Core/Trigger/Action/GetVectorLerpTAction/GetColorableLerpTAction/GetColorableLerpTAction.h>
#include <Engine/Core/Trigger/Action/GetQuaternionLerpTAction/GetQuaternionLerpTAction/GetQuaternionLerpTAction.h>
#include <Engine/Core/Trigger/Action/GetQuaternionLerpTAction/GetRotatableLerpTAction/GetRotatableLerpTAction.h>
#include <Engine/Core/Trigger/Action/EnableTextureFlipAction/EnableTextureFlipAction.h>
#include <Engine/Core/Trigger/Action/ChangeFloatLerpTAction/ChangeFloatLerpTAction.h>
#include <Engine/Core/Trigger/Action/GetFloatLerpTAction/GetFloatLerpTAction.h>
#include <Engine/Core/Trigger/Action/GetTextureSizeAction/GetTextureSizeAction.h>
#include <Engine/Core/Trigger/Action/GetListLengthAction/GetListLengthAction.h>
#include <Engine/Core/Trigger/Action/GetQuaternionLerpPathAction/GetQuaternionLerpPathAction.h>
#include <Engine/Core/Trigger/Action/ChangeRandomSeedAction/ChangeRandomSeedAction.h>
#include <Engine/Core/Trigger/Action/GetRandomValueAction/GetRandomBooleanAction/GetRandomBooleanAction.h>
#include <Engine/Core/Trigger/Action/GetRandomValueAction/GetRandomIntegerAction/GetRandomIntegerAction.h>
#include <Engine/Core/Trigger/Action/GetRandomValueAction/GetRandomFloatAction/GetRandomFloatAction.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemIntegerAction/ChangeItemIntegerAction.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemFloatAction/ChangeItemFloatAction.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemBooleanAction/ChangeItemBooleanAction.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemStringAction/ChangeItemStringAction.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemVector2Action/ChangeItemVector2Action.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemVector3Action/ChangeItemVector3Action.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemQuaternionAction/ChangeItemQuaternionAction.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemTranslatableAction/ChangeItemTranslatableAction.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemRotatableAction/ChangeItemRotatableAction.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemColorableAction/ChangeItemColorableAction.h>
#include <Engine/Core/Trigger/Action/ChangeItemValueAction/ChangeItemScalableAction/ChangeItemScalableAction.h>
#include <Engine/Core/Trigger/Action/CopyListAction/CopyListAction.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListIntegerAction/ChangeListIntegerAction.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListFloatAction/ChangeListFloatAction.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListBooleanAction/ChangeListBooleanAction.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListStringAction/ChangeListStringAction.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListVector2Action/ChangeListVector2Action.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListVector3Action/ChangeListVector3Action.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListQuaternionAction/ChangeListQuaternionAction.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListTranslatableAction/ChangeListTranslatableAction.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListRotatableAction/ChangeListRotatableAction.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListColorableAction/ChangeListColorableAction.h>
#include <Engine/Core/Trigger/Action/ChangeListValueAction/ChangeListScalableAction/ChangeListScalableAction.h>
#include <Engine/Core/Trigger/Action/RemoveFromListAction/RemoveIndexFromListAction/RemoveIndexFromListAction.h>
#include <Engine/Core/Trigger/Action/RemoveFromListAction/RemoveItemFromListAction/RemoveItemFromListAction.h>
#include <Engine/Core/Trigger/Action/AddToListAction/AddToListAction.h>
#include <Engine/Core/Trigger/Action/InverseListAction/InverseListAction.h>
#include <Engine/Core/Trigger/Action/GetItemIndexAction/GetItemIndexAction.h>
#include <Engine/Core/Trigger/Action/GetDataFromItemAction/GetDataFromItemAction.h>
#include <Engine/Core/Trigger/Action/RandomizeListAction/RandomizeListAction.h>
#include <Engine/Core/Trigger/Action/GetAmountOfItemsAction/GetAmountOfItemsAction.h>
#include <Engine/Core/Trigger/Action/ClearListAction/ClearListAction.h>
#include <Engine/Core/Trigger/Action/CreateListAction/CreateListAction.h>
#include <Engine/Core/Trigger/Action/CreateVariableAction/CreateIntegerVariableAction/CreateIntegerVariableAction.h>
#include <Engine/Core/Trigger/Action/CreateVariableAction/CreateFloatVariableAction/CreateFloatVariableAction.h>
#include <Engine/Core/Trigger/Action/CreateVariableAction/CreateBooleanVariableAction/CreateBooleanVariableAction.h>
#include <Engine/Core/Trigger/Action/CreateVariableAction/CreateStringVariableAction/CreateStringVariableAction.h>
#include <Engine/Core/Trigger/Action/CreateVariableAction/CreateVector2VariableAction/CreateVector2VariableAction.h>
#include <Engine/Core/Trigger/Action/CreateVariableAction/CreateVector3VariableAction/CreateVector3VariableAction.h>
#include <Engine/Core/Trigger/Action/CreateVariableAction/CreateQuaternionVariableAction/CreateQuaternionVariableAction.h>
#include <Engine/Core/Trigger/Action/ChangeBackgroundColorAction/ChangeBackgroundColorAction.h>
#include <Engine/Core/Trigger/Action/GetColorAction/GetColorRGBAction/GetColorRGBAction.h>
#include <Engine/Core/Trigger/Action/GetColorAction/GetColorHSLAction/GetColorHSLAction.h>
#include <Engine/Core/Trigger/Action/GetColorComponentAction/GetAlphaAction/GetAlphaAction.h>
#include <Engine/Core/Trigger/Action/GetColorComponentAction/GetRedAction/GetRedAction.h>
#include <Engine/Core/Trigger/Action/GetColorComponentAction/GetGreenAction/GetGreenAction.h>
#include <Engine/Core/Trigger/Action/GetColorComponentAction/GetBlueAction/GetBlueAction.h>
#include <Engine/Core/Trigger/Action/GetColorComponentAction/GetHueAction/GetHueAction.h>
#include <Engine/Core/Trigger/Action/GetColorComponentAction/GetSaturationAction/GetSaturationAction.h>
#include <Engine/Core/Trigger/Action/GetColorComponentAction/GetLightnessAction/GetLightnessAction.h>
#include <Engine/Core/Trigger/Action/ChangeColorAction/ChangeColorRGBAction/ChangeColorRGBAction.h>
#include <Engine/Core/Trigger/Action/ChangeColorAction/ChangeColorHSLAction/ChangeColorHSLAction.h>
#include <Engine/Core/Trigger/Action/ChangeColorComponentAction/ChangeAlphaAction/ChangeAlphaAction.h>
#include <Engine/Core/Trigger/Action/ChangeColorComponentAction/ChangeRedAction/ChangeRedAction.h>
#include <Engine/Core/Trigger/Action/ChangeColorComponentAction/ChangeGreenAction/ChangeGreenAction.h>
#include <Engine/Core/Trigger/Action/ChangeColorComponentAction/ChangeBlueAction/ChangeBlueAction.h>
#include <Engine/Core/Trigger/Action/ChangeColorComponentAction/ChangeHueAction/ChangeHueAction.h>
#include <Engine/Core/Trigger/Action/ChangeColorComponentAction/ChangeSaturationAction/ChangeSaturationAction.h>
#include <Engine/Core/Trigger/Action/ChangeColorComponentAction/ChangeLightnessAction/ChangeLightnessAction.h>
#include <Engine/Core/Trigger/Action/GetScaleAction/GetScaleAction.h>
#include <Engine/Core/Trigger/Action/DisplaceScaleAction/DisplaceScaleAction.h>
#include <Engine/Core/Trigger/Action/ReplaceScaleAction/ReplaceScaleAction.h>
#include <Engine/Core/Trigger/Action/GetPositionAction/GetPositionAction.h>
#include <Engine/Core/Trigger/Action/DisplacePositionAction/DisplacePositionAction.h>
#include <Engine/Core/Trigger/Action/ReplacePositionAction/ReplacePositionAction.h>
#include <Engine/Core/Trigger/Action/GetRotationAction/GetRotationAction.h>
#include <Engine/Core/Trigger/Action/ReplaceRotationAction/ReplaceRotationAction.h>
#include <Engine/Core/Trigger/Action/DisplaceRotationAction/DisplaceRotationAction.h>
#include <Engine/Core/Trigger/Action/ChangePlaneNormalAction/ChangePlaneNormalAction.h>
#include <Engine/Core/Trigger/Action/ChangeViewingPointAction/ChangeViewingPointAction.h>
#include <Engine/Core/Trigger/Action/ChangeMeshAction/ChangeMeshAction.h>
#include <Engine/Core/Trigger/Action/ChangeHitboxAction/ChangeHitboxAction.h>
#include <Engine/Core/Trigger/Action/CreateQuadAction/CreateQuadAction.h>
#include <Engine/Core/Trigger/Action/CreateBoxAction/CreateBoxAction.h>
#include <Engine/Core/Trigger/Action/TiledSpaceFillAction/TiledSpaceFillAction.h>
#include <Engine/Core/Trigger/Action/CreateBoxTextureMapAction/CreateBoxTextureMapAction.h>
#include <Engine/Core/Trigger/Action/ChangeBoxTextureMapAction/ChangeBoxTextureMapAction.h>
#include <Engine/Core/Trigger/Action/ChangeDeltaScaleAction/ChangeDeltaScaleAction.h>
#include <Engine/Core/Trigger/Action/ChangeIntersectionModeAction/ChangeIntersectionModeAction.h>
#include <Engine/Core/Trigger/Action/EnableBackFaceCullingAction/EnableBackFaceCullingAction.h>
#include <Engine/Core/Trigger/Action/EnablePositionOffsetAction/EnablePositionOffsetAction.h>
#include <Engine/Core/Trigger/Action/ChangeFrontTextureAction/ChangeFrontTextureAction.h>
#include <Engine/Core/Trigger/Action/ChangeBackTextureAction/ChangeBackTextureAction.h>
#include <Engine/Core/Trigger/Action/ChangeFrontTexturedAnimationAction/ChangeFrontTexturedAnimationAction.h>
#include <Engine/Core/Trigger/Action/ChangeBackTexturedAnimationAction/ChangeBackTexturedAnimationAction.h>
#include <Engine/Core/Trigger/Action/EnableShowCursorAction/EnableShowCursorAction.h>
#include <Engine/Core/Trigger/Action/EnableZBufferAction/EnableZBufferAction.h>
#include <Engine/Core/Trigger/Action/CreateKeyboardEventAction/CreateKeyboardEventAction.h>
#include <Engine/Core/Trigger/Action/PickSceneAction/PickSceneAction.h>
#include <Engine/Core/Trigger/Action/AddToLayerAction/AddToLayerAction.h>
#include <Engine/Core/Trigger/Action/RemoveFromLayerAction/RemoveFromLayerAction.h>
#include <Engine/Core/Trigger/Action/AddToUpdateListAction/AddToUpdateListAction.h>
#include <Engine/Core/Trigger/Action/RemoveFromUpdateListAction/RemoveFromUpdateListAction.h>
#include <Engine/Core/Trigger/Action/AddToRenderListAction/AddToRenderListAction.h>
#include <Engine/Core/Trigger/Action/RemoveFromRenderListAction/RemoveFromRenderListAction.h>
#include <Engine/Core/Trigger/Action/ChangeCameraAction/ChangeCameraAction.h>
#include <Engine/Core/Trigger/Action/GetSelectRayAction/GetSelectRayAction.h>
#include <Engine/Core/Trigger/Action/ChangeProjectionModeAction/ChangeProjectionModeAction.h>
#include <Engine/Core/Trigger/Action/PickCameraAction/PickCameraAction.h>
#include <Engine/Core/Trigger/Action/ChangeFloatLerpModeAction/ChangeFloatLerpModeAction.h>
#include <Engine/Core/Trigger/Action/ChangeFloatLerpSpeedAction/ChangeFloatLerpSpeedAction.h>
#include <Engine/Core/Trigger/Action/CreateFloatLerpAction/CreateFloatLerpAction.h>
#include <Engine/Core/Trigger/Action/CreateTiledSpaceAction/CreateTiledSpaceAction.h>
#include <Engine/Core/Trigger/Action/ChangeTiledSpaceSizeAction/ChangeTiledSpaceSizeAction.h>
#include <Engine/Core/Trigger/Action/CreateSolidTileAction/CreateSolidTileAction.h>
#include <Engine/Core/Trigger/Action/CreateEmptyTileAction/CreateEmptyTileAction.h>
#include <Engine/Core/Trigger/Action/ChangeRenderTargetAction/ChangeRenderTargetAction.h>
#include <Engine/Core/Trigger/Action/CreateBrushAction/CreateBrushAction.h>
#include <Engine/Core/Trigger/Action/CreateQuaternionLerpAction/CreateQuaternionLerpAction.h>
#include <Engine/Core/Trigger/Action/CreateVectorLerpAction/CreateVectorLerpAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTAction/StreamingFloatTAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTAlphaAction/StreamingFloatTAlphaAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTAnimationFrameAction/StreamingFloatTAnimationFrameAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTRedAction/StreamingFloatTRedAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTGreenAction/StreamingFloatTGreenAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTBlueAction/StreamingFloatTBlueAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTHueAction/StreamingFloatTHueAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTSaturationAction/StreamingFloatTSaturationAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTLightnessAction/StreamingFloatTLightnessAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatTAction/StreamingFloatTDeltaScaleAction/StreamingFloatTDeltaScaleAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatCurrentAction/StreamingFloatCurrentAction.h>
#include <Engine/Core/Trigger/Action/ChangeFloatLerpTargetAction/ChangeFloatLerpFloatTargetAction/ChangeFloatLerpFloatTargetAction.h>
#include <Engine/Core/Trigger/Action/ChangeFloatLerpTargetAction/ChangeFloatLerpIntegerTargetAction/ChangeFloatLerpIntegerTargetAction.h>
#include <Engine/Core/Trigger/Action/StreamingFloatDeltaAction/StreamingFloatDeltaAction.h>
#include <Engine/Core/Trigger/Action/ChangeVectorLerpModeAction/ChangeVectorLerpModeAction.h>
#include <Engine/Core/Trigger/Action/GetLineAngleZAction/GetLineAngleZAction.h>
#include <Engine/Core/Trigger/Action/GetVectorAngleAction/GetVector3AngleAction/GetVector3AngleAction.h>
#include <Engine/Core/Trigger/Action/GetVectorAngleAction/GetVector2AngleAction/GetVector2AngleAction.h>
#include <Engine/Core/Trigger/Action/CreateRotationAction/CreateRotationAction.h>
#include <Engine/Core/Trigger/Action/ChangeFloatLerpAction/ChangeFloatLerpAction.h>
#include <Engine/Core/Trigger/Action/ChangePlayingModeAction/ChangePlayingModeAction.h>
#include <Engine/Core/Trigger/Action/ChangePlayingStateAction/ChangePlayingStateAction.h>
#include <Engine/Core/Trigger/Action/ChangePlayingDurationInSecAction/ChangePlayingDurationInSecAction.h>
#include <Engine/Core/Trigger/Action/ChangeDistanceToViewingPointAction/ChangeDistanceToViewingPointAction.h>
#include <Engine/Core/Trigger/Action/CameraLookAtAction/CameraLookAtAction.h>
#include <Engine/Core/Trigger/Action/StreamingQuaternionCurrentAction/StreamingQuaternionCurrentAction/StreamingQuaternionCurrentAction.h>
#include <Engine/Core/Trigger/Action/StreamingQuaternionCurrentAction/StreamingRotatableCurrentAction/StreamingRotatableCurrentAction.h>
#include <Engine/Core/Trigger/Action/StreamingQuaternionDeltaAction/StreamingQuaternionDeltaAction/StreamingQuaternionDeltaAction.h>
#include <Engine/Core/Trigger/Action/StreamingQuaternionDeltaAction/StreamingRotatableDeltaAction/StreamingRotatableDeltaAction.h>
#include <Engine/Core/Trigger/Action/StreamingVectorDeltaAction/StreamingVectorDeltaAction/StreamingVectorDeltaAction.h>
#include <Engine/Core/Trigger/Action/StreamingVectorDeltaAction/StreamingTranslatableDeltaAction/StreamingTranslatableDeltaAction.h>
#include <Engine/Core/Trigger/Action/StreamingVectorDeltaAction/StreamingScalableDeltaAction/StreamingScalableDeltaAction.h>
#include <Engine/Core/Trigger/Action/StreamingVectorDeltaAction/StreamingColorableDeltaAction/StreamingColorableDeltaAction.h>
#include <Engine/Core/Trigger/Action/StreamingVectorCurrentAction/StreamingColorableCurrentAction/StreamingColorableCurrentAction.h>
#include <Engine/Core/Trigger/Action/StreamingVectorCurrentAction/StreamingVectorCurrentAction/StreamingVectorCurrentAction.h>
#include <Engine/Core/Trigger/Action/StreamingVectorCurrentAction/StreamingTranslatableCurrentAction/StreamingTranslatableCurrentAction.h>
#include <Engine/Core/Trigger/Action/StreamingVectorCurrentAction/StreamingScalableCurrentAction/StreamingScalableCurrentAction.h>
#include <Engine/Core/Trigger/Action/CheckLineInImageAction/CheckLineInImageAction.h>
#include <Engine/Core/Trigger/Action/CheckLineInPolygonAction/CheckLineInPolygonAction.h>
#include <Engine/Core/Trigger/Action/CheckLineInSurfaceAction/CheckLineInSurfaceAction.h>
#include <Engine/Core/Trigger/Action/SetTwoVectorsAction/SetTwoVectorsAction/SetTwoVectorsAction.h>
#include <Engine/Core/Trigger/Action/SetTwoVectorsAction/SetTwoTranslatablesAction/SetTwoTranslatablesAction.h>
#include <Engine/Core/Trigger/Action/SetTwoVectorsAction/SetTwoScalablesAction/SetTwoScalablesAction.h>
#include <Engine/Core/Trigger/Action/SetTwoVectorsAction/SetTwoColorablesAction/SetTwoColorablesAction.h>
#include <Engine/Core/Trigger/Action/ChangeControlVectorsAction/ChangeControlVectorsAction/ChangeControlVectorsAction.h>
#include <Engine/Core/Trigger/Action/ChangeControlVectorsAction/ChangeControlTranslatablesAction/ChangeControlTranslatablesAction.h>
#include <Engine/Core/Trigger/Action/ChangeControlVectorsAction/ChangeControlScalablesAction/ChangeControlScalablesAction.h>
#include <Engine/Core/Trigger/Action/ChangeControlVectorsAction/ChangeControlColorablesAction/ChangeControlColorablesAction.h>
#include <Engine/Core/Trigger/Action/ChangeControlQuaternionsAction/ChangeControlQuaternionsAction/ChangeControlQuaternionsAction.h>
#include <Engine/Core/Trigger/Action/ChangeControlQuaternionsAction/ChangeControlRotatablesAction/ChangeControlRotatablesAction.h>
#include <Engine/Core/Trigger/Action/SetTwoQuaternionsAction/SetTwoQuaternionsAction/SetTwoQuaternionsAction.h>
#include <Engine/Core/Trigger/Action/SetTwoQuaternionsAction/SetTwoRotatablesAction/SetTwoRotatablesAction.h>
#include <Engine/Core/Trigger/Action/ChangeCollisionGroupAction/ChangeCollisionGroupAction.h>
#include <Engine/Core/Trigger/Action/CheckCollisionAction/CheckCollisionGroupGroupAction/CheckCollisionGroupGroupAction.h>
#include <Engine/Core/Trigger/Action/CheckCollisionAction/CheckCollisionObjectObjectAction/CheckCollisionObjectObjectAction.h>
#include <Engine/Core/Trigger/Action/CheckCollisionAction/CheckCollisionObjectGroupAction/CheckCollisionObjectGroupAction.h>
#include <Engine/Core/Trigger/Action/EnableCollisionCheckingAction/EnableCollisionCheckingAction.h>
#include <Engine/Core/Trigger/Action/EnableCollisionPolygonsInfoAction/EnableCollisionPolygonsInfoAction.h>
#include <Engine/Core/Trigger/Action/SetDataToControlVectorAction/SetDataToControlVectorAction/SetDataToControlVectorAction.h>
#include <Engine/Core/Trigger/Action/SetDataToControlVectorAction/SetDataToControlTranslatableAction/SetDataToControlTranslatableAction.h>
#include <Engine/Core/Trigger/Action/SetDataToControlVectorAction/SetDataToControlScalableAction/SetDataToControlScalableAction.h>
#include <Engine/Core/Trigger/Action/SetDataToControlVectorAction/SetDataToControlColorableAction/SetDataToControlColorableAction.h>
#include <Engine/Core/Trigger/Action/EnableTriggersBlockAction/EnableTriggersBlockAction.h>
#include <Engine/Core/Trigger/Action/SetDataToControlQuaternionAction/SetDataToControlQuaternionAction/SetDataToControlQuaternionAction.h>
#include <Engine/Core/Trigger/Action/SetDataToControlQuaternionAction/SetDataToControlRotatableAction/SetDataToControlRotatableAction.h>

#endif 