#ifndef EVENTS_H
#define EVENTS_H
#include <Engine/Core/Trigger/Event/ChangeNameEvent/ChangeNameEvent.h>
#include <Engine/Core/Trigger/Event/DestroyObjectEvent/DestroyObjectEvent.h>
#include <Engine/Core/Trigger/Event/CreateObjectEvent/CreateObjectEvent.h>
#include <Engine/Core/Trigger/Event/SendMessageEvent/SendMessageEvent.h>
#include <Engine/Core/Trigger/Event/TimerFinishEvent/TimerFinishEvent.h>
#include <Engine/Core/Trigger/Event/FloatLerpFinishEvent/FloatLerpFinishEvent.h>
#include <Engine/Core/Trigger/Event/FloatLerpStartEvent/FloatLerpStartEvent.h>
#include <Engine/Core/Trigger/Event/PickSceneEvent/PickSceneEvent.h>
#include <Engine/Core/Trigger/Event/EnablePropertyEvent/EnablePropertyEvent.h>
#include <Engine/Core/Trigger/Event/AddToLayerEvent/AddToLayerEvent.h>
#include <Engine/Core/Trigger/Event/RemoveFromLayerEvent/RemoveFromLayerEvent.h>
#include <Engine/Core/Trigger/Event/AddToUpdateListEvent/AddToUpdateListEvent.h>
#include <Engine/Core/Trigger/Event/RemoveFromUpdateListEvent/RemoveFromUpdateListEvent.h>
#include <Engine/Core/Trigger/Event/AddToRenderListEvent/AddToRenderListEvent.h>
#include <Engine/Core/Trigger/Event/RemoveFromRenderListEvent/RemoveFromRenderListEvent.h>
#include <Engine/Core/Trigger/Event/ChangeCameraEvent/ChangeCameraEvent.h>
#include <Engine/Core/Trigger/Event/EnablePositionOffsetEvent/EnablePositionOffsetEvent.h>
#include <Engine/Core/Trigger/Event/ChangeBackTextureEvent/ChangeBackTextureEvent.h>
#include <Engine/Core/Trigger/Event/ChangeFrontTextureEvent/ChangeFrontTextureEvent.h>
#include <Engine/Core/Trigger/Event/ChangeFrontTexturedAnimationEvent/ChangeFrontTexturedAnimationEvent.h>
#include <Engine/Core/Trigger/Event/ChangeBackTexturedAnimationEvent/ChangeBackTexturedAnimationEvent.h>
#include <Engine/Core/Trigger/Event/ChangeAnimationFrameEvent/ChangeAnimationFrameEvent.h>
#include <Engine/Core/Trigger/Event/ChangeAtlasEvent/ChangeAtlasEvent.h>
#include <Engine/Core/Trigger/Event/PlayerControlFinishEvent/PlayerControlFinishEvent.h>
#include <Engine/Core/Trigger/Event/TriggerFinishEvent/TriggerFinishEvent.h>
#include <Engine/Core/Trigger/Event/PickCameraEvent/PickCameraEvent.h>
#include <Engine/Core/Trigger/Event/ChangeFloatLerpEvent/ChangeFloatLerpEvent.h>
#include <Engine/Core/Trigger/Event/ChangeMeshEvent/ChangeMeshEvent.h>
#include <Engine/Core/Trigger/Event/ChangeHitboxEvent/ChangeHitboxEvent.h>
#include <Engine/Core/Trigger/Event/ChangePlayingStateEvent/ChangePlayingStateEvent.h>
#include <Engine/Core/Trigger/Event/ChangeValueEvent/ChangeIntegerValueEvent/ChangeIntegerValueEvent.h>
#include <Engine/Core/Trigger/Event/ChangeValueEvent/ChangeFloatValueEvent/ChangeFloatValueEvent.h>
#include <Engine/Core/Trigger/Event/ChangeValueEvent/ChangeBooleanValueEvent/ChangeBooleanValueEvent.h>
#include <Engine/Core/Trigger/Event/ChangeValueEvent/ChangeStringValueEvent/ChangeStringValueEvent.h>
#include <Engine/Core/Trigger/Event/ChangeValueEvent/ChangeVector2ValueEvent/ChangeVector2ValueEvent.h>
#include <Engine/Core/Trigger/Event/ChangeValueEvent/ChangeVector3ValueEvent/ChangeVector3ValueEvent.h>
#include <Engine/Core/Trigger/Event/ChangeValueEvent/ChangeQuaternionValueEvent/ChangeQuaternionValueEvent.h>
#include <Engine/Core/Trigger/Event/CollisionBetweenObjectsEvent/CollisionBetweenObjectsEvent.h>
#include <Engine/Core/Trigger/Event/ChangePlayingModeEvent/ChangePlayingModeEvent.h>

#endif 